ltm_fields = [
    "revenue_new_cust","revenue_ncust__trend","revenue_repeat_cust","revenue_rcust__trend","revenue_demand","revenue_maint","revenue_estimates","revenue_projects","revenue_total","revenue_pace","revenue_rev_trend",
    "single_jobs_new_cust","single_jobs_ncust__trend","single_jobs_new_cust_ib","single_jobs_new_cust_ob","single_jobs_r_cust_ob","single_jobs_r_cust_ib","single_jobs_r_cust_ib_pace","single_jobs_r_ib_trend","single_jobs_repeat_cust","single_jobs_demand","single_jobs_maint","single_jobs_total","single_jobs_pace","single_jobs_sj_trend",
    "gba_new_cust","gba_r_cust","gba_demand","gba_maint","gba_actual","gba_pace","gba_trend",
    "sold_estimates_actual","sold_estimates_pace","sold_estimates_trend",
    "manpower_sj_qty","manpower_svc_avg","manpower_svc_pj_qty","manpower_svc_prj_avg","manpower_repl_pj_qty","manpower_installer_avg",
    "sold_hours_total_sold_hrs",
    "sj__usd_100_new_cust","sj__usd_100_repeat_cust","sj__usd_100_demand","sj__usd_100_maint","sj__usd_100_total",
    "recalls_total",
    "sj_repair_pct_new_cust","sj_repair_pct_repeat_cust","sj_repair_pct_demand","sj_repair_pct_maint","sj_repair_pct_total",
    "sj_repair_avg_usd_new_cust","sj_repair_avg_usd_repeat_cust","sj_repair_avg_usd_demand","sj_repair_avg_usd_maint","sj_repair_avg_usd_total",
    "opportunity_to_pct_new_cust","opportunity_to_pct_repeat_cust","opportunity_to_pct_demand","opportunity_to_pct_maint","opportunity_to_pct_est","opportunity_to_pct_total",
    "to_conversion_pct_new_cust","to_conversion_pct_repeat_cust","to_conversion_pct_demand","to_conversion_pct_maint","to_conversion_pct_total",
    "conversion_usd_avg_new_cust","conversion_usd_avg_repeat_cust","conversion_usd_avg_demand","conversion_usd_avg_maint","conversion_usd_avg_total",
    "sj_mktestimates_new_cust","sj_mktestimates_repeat_cust","sj_mktestimates_estimates","sj_mktestimates_total","sj_mktestimates_pace","sj_mktestimates_est_trend",
    "sj_mkte_conv_pct_new_cust","sj_mkte_conv_pct_repeat_cust","sj_mkte_conv_pct_total",
    "sj_mkte_conv_usd_new_cust","sj_mkte_conv_usd_repeat_cust","sj_mkte_conv_usd_estimates","sj_mkte_conv_usd_total",
    "airflow_prj_mix_pct_new_cust","airflow_prj_mix_pct_repeat_cust","airflow_prj_mix_pct_total",
    "af_prj_avg_usd_new_cust","af_prj_avg_usd_repeat_cust","af_prj_avg_usd_total",
    "equip_mix_pct_new_cust","equip_mix_pct_repeat_cust","equip_mix_pct_total",
    "equip_avg_usd_new_cust","equip_avg_usd_repeat_cust","equip_avg_usd_total",
    "svc_prj_pct_new_cust","svc_prj_pct_repeat_cust","svc_prj_pct_total",
    "svc_prj_avg_usd_new_cust","svc_prj_avg_usd_repeat_cust","svc_prj_avg_usd_total"
]

ltm_fields_array = [
    ('revenue_new_cust','Revenue','Revenue New Cust'),
    ('revenue_ncust__trend','Revenue','Revenue NCust  Trend'),
    ('revenue_repeat_cust','Revenue','Revenue Repeat Cust'),
    ('revenue_rcust__trend','Revenue','Revenue RCust  Trend'),
    ('revenue_demand','Revenue','Revenue Demand'),
    ('revenue_maint','Revenue','Revenue Maint'),
    ('revenue_estimates','Revenue','Revenue Estimates'),
    ('revenue_projects','Revenue','Revenue Projects'),
    ('revenue_total','Revenue','Revenue TOTAL'),
    ('revenue_pace','Revenue','Revenue PACE'),
    ('revenue_rev_trend','Revenue','Revenue Rev Trend'),
    ('single_jobs_new_cust','Single Jobs','Single Jobs New Cust'),
    ('single_jobs_ncust__trend','Single Jobs','Single Jobs NCust  Trend'),
    ('single_jobs_new_cust_ib','Single Jobs','Single Jobs New Cust IB'),
    ('single_jobs_new_cust_ob','Single Jobs','Single Jobs New Cust OB'),
    ('single_jobs_r_cust_ob','Single Jobs','Single Jobs R Cust OB'),
    ('single_jobs_r_cust_ib','Single Jobs','Single Jobs R Cust IB'),
    ('single_jobs_r_cust_ib_pace','Single Jobs','Single Jobs R Cust IB PACE'),
    ('single_jobs_r_ib_trend','Single Jobs','Single Jobs R IB Trend'),
    ('single_jobs_repeat_cust','Single Jobs','Single Jobs Repeat Cust'),
    ('single_jobs_demand','Single Jobs','Single Jobs Demand'),
    ('single_jobs_maint','Single Jobs','Single Jobs Maint'),
    ('single_jobs_total','Single Jobs','Single Jobs Total'),
    ('single_jobs_pace','Single Jobs','Single Jobs PACE'),
    ('single_jobs_sj_trend','Single Jobs','Single Jobs SJ Trend'),
    ('gba_new_cust','GBA','GBA New Cust'),
    ('gba_r_cust','GBA','GBA Repeat Cust'),
    ('gba_demand','GBA','GBA Demand'),
    ('gba_maint','GBA','GBA Maint'),
    ('gba_actual','GBA','GBA actual'),
    ('gba_pace','GBA','GBA pace'),
    ('gba_trend','GBA','GBA Trend'),
    ('sold_estimates_actual','SOLD ESTIMATES','SOLD ESTIMATES Actual'),
    ('sold_estimates_pace','SOLD ESTIMATES','SOLD ESTIMATES PACE'),
    ('sold_estimates_trend','SOLD ESTIMATES','SOLD ESTIMATES Trend'),
    ('manpower_sj_qty','MANPOWER','MANPOWER SJ Qty'),
    ('manpower_svc_avg','MANPOWER','MANPOWER Svc Avg'),
    ('manpower_svc_pj_qty','MANPOWER','MANPOWER Svc Pj Qty'),
    ('manpower_svc_prj_avg','MANPOWER','MANPOWER Svc Prj Avg'),
    ('manpower_repl_pj_qty','MANPOWER','MANPOWER Repl Pj Qty'),
    ('manpower_installer_avg','MANPOWER','MANPOWER Installer Avg'),
    ('sold_hours_total_sold_hrs','SOLD HOURS','SOLD HOURS Total Sold Hrs'),
    ('sj__usd_100_new_cust','SJ<$100','SJ<$100 New Cust'),
    ('sj__usd_100_repeat_cust','SJ<$100','SJ<$100 Repeat Cust'),
    ('sj__usd_100_demand','SJ<$100','SJ<$100 Demand'),
    ('sj__usd_100_maint','SJ<$100','SJ<$100 Maint'),
    ('sj__usd_100_total','SJ<$100','SJ<$100 Total'),
    ('recalls_total','Recalls','Recalls Total'),
    ('sj_repair_pct_new_cust','SJ Repair %','SJ Repair % New Cust'),
    ('sj_repair_pct_repeat_cust','SJ Repair %','SJ Repair % Repeat Cust'),
    ('sj_repair_pct_demand','SJ Repair %','SJ Repair % Demand'),
    ('sj_repair_pct_maint','SJ Repair %','SJ Repair % Maint'),
    ('sj_repair_pct_total','SJ Repair %','SJ Repair % Total'),
    ('sj_repair_avg_usd_new_cust','SJ Repair Avg$$','SJ Repair Avg$$ New Cust'),
    ('sj_repair_avg_usd_repeat_cust','SJ Repair Avg$$','SJ Repair Avg$$ Repeat Cust'),
    ('sj_repair_avg_usd_demand','SJ Repair Avg$$','SJ Repair Avg$$ Demand'),
    ('sj_repair_avg_usd_maint','SJ Repair Avg$$','SJ Repair Avg$$ Maint'),
    ('sj_repair_avg_usd_total','SJ Repair Avg$$','SJ Repair Avg$$ Total'),
    ('opportunity_to_pct_new_cust','Opportunity TO %','Opportunity TO % New Cust'),
    ('opportunity_to_pct_repeat_cust','Opportunity TO %','Opportunity TO % Repeat Cust'),
    ('opportunity_to_pct_demand','Opportunity TO %','Opportunity TO % Demand'),
    ('opportunity_to_pct_maint','Opportunity TO %','Opportunity TO % Maint'),
    ('opportunity_to_pct_est','Opportunity TO %','Opportunity TO % Est'),
    ('opportunity_to_pct_total','Opportunity TO %','Opportunity TO % Total'),
    ('to_conversion_pct_new_cust','TO Conversion %','TO Conversion % New Cust'),
    ('to_conversion_pct_repeat_cust','TO Conversion %','TO Conversion % Repeat Cust'),
    ('to_conversion_pct_demand','TO Conversion %','TO Conversion % Demand'),
    ('to_conversion_pct_maint','TO Conversion %','TO Conversion % Maint'),
    ('to_conversion_pct_total','TO Conversion %','TO Conversion % Total'),
    ('conversion_usd_avg_new_cust','Conversion $AVG','Conversion $AVG New Cust'),
    ('conversion_usd_avg_repeat_cust','Conversion $AVG','Conversion $AVG Repeat Cust'),
    ('conversion_usd_avg_demand','Conversion $AVG','Conversion $AVG Demand'),
    ('conversion_usd_avg_maint','Conversion $AVG','Conversion $AVG Maint'),
    ('conversion_usd_avg_total','Conversion $AVG','Conversion $AVG Total'),
    ('sj_mktestimates_new_cust','SJ MKTEstimates','SJ MKTEstimates New Cust'),
    ('sj_mktestimates_repeat_cust','SJ MKTEstimates','SJ MKTEstimates Repeat Cust'),
    ('sj_mktestimates_estimates','SJ MKTEstimates','SJ MKTEstimates Estimates'),
    ('sj_mktestimates_total','SJ MKTEstimates','SJ MKTEstimates Total'),
    ('sj_mktestimates_pace','SJ MKTEstimates','SJ MKTEstimates PACE'),
    ('sj_mktestimates_est_trend','SJ MKTEstimates','SJ MKTEstimates SJ Trend'),
    ('sj_mkte_conv_pct_new_cust','SJ MKTE Conv %','SJ MKTE Conv % New Cust'),
    ('sj_mkte_conv_pct_repeat_cust','SJ MKTE Conv %','SJ MKTE Conv % Repeat Cust'),
    ('sj_mkte_conv_pct_total','SJ MKTE Conv %','SJ MKTE Conv % Total'),
    ('sj_mkte_conv_usd_new_cust','SJ MKTE Conv $','SJ MKTE Conv $ New Cust'),
    ('sj_mkte_conv_usd_repeat_cust','SJ MKTE Conv $','SJ MKTE Conv $ Repeat Cust'),
    ('sj_mkte_conv_usd_estimates','SJ MKTE Conv $','SJ MKTE Conv $ Estimates'),
    ('sj_mkte_conv_usd_total','SJ MKTE Conv $','SJ MKTE Conv $ Total'),
    ('airflow_prj_mix_pct_new_cust','Airflow PRJ MIX %','Airflow PRJ MIX % New Cust'),
    ('airflow_prj_mix_pct_repeat_cust','Airflow PRJ MIX %','Airflow PRJ MIX % Repeat Cust'),
    ('airflow_prj_mix_pct_total','Airflow PRJ MIX %','Airflow PRJ MIX % Total'),
    ('af_prj_avg_usd_new_cust','AF PRJ AVG $','AF PRJ AVG $ New Cust'),
    ('af_prj_avg_usd_repeat_cust','AF PRJ AVG $','AF PRJ AVG $ Repeat Cust'),
    ('af_prj_avg_usd_total','AF PRJ AVG $','AF PRJ AVG $ Total'),
    ('equip_mix_pct_new_cust','Equip MIX %','Equip MIX % New Cust'),
    ('equip_mix_pct_repeat_cust','Equip MIX %','Equip MIX % Repeat Cust'),
    ('equip_mix_pct_total','Equip MIX %','Equip MIX % Total'),
    ('equip_avg_usd_new_cust','Equip AVG $','Equip AVG $ New Cust'),
    ('equip_avg_usd_repeat_cust','Equip AVG $','Equip AVG $ Repeat Cust'),
    ('equip_avg_usd_total','Equip AVG $','Equip AVG $ Total'),
    ('svc_prj_pct_new_cust','SVC PRJ %','SVC PRJ % New Cust'),
    ('svc_prj_pct_repeat_cust','SVC PRJ %','SVC PRJ % Repeat Cust'),
    ('svc_prj_pct_total','SVC PRJ %','SVC PRJ % Total'),
    ('svc_prj_avg_usd_new_cust','SVC PRJ AVG $','SVC PRJ AVG $ New Cust'),
    ('svc_prj_avg_usd_repeat_cust','SVC PRJ AVG $','SVC PRJ AVG $ Repeat Cust'),
    ('svc_prj_avg_usd_total','SVC PRJ AVG $','SVC PRJ AVG $ Total')
]

union_queries = []

# Iterar sobre cada compañía en la lista
for field, tag, subtag in ltm_fields_array:
    union_queries.append(
        f"\nSELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.{field}, 0) AS tag_value, cm.month_offset, CAST('{tag}' AS STRING) AS tag, CAST('{subtag}' AS STRING) AS subtag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month\n"
    )

# Unir todas las consultas con UNION ALL
final_sql = f"""
, ltm_kpis_data AS (
    {' UNION ALL '.join(union_queries)}
"""
#print(final_sql)

with open('consulta_sql.txt', 'w', encoding='utf-8') as file:
    file.write(final_sql)
