    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_total, 0)               AS total, cm.month_offset, CAST('Revenue' AS STRING) AS tag             FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_total, 0)           AS total, cm.month_offset, CAST('Single Jobs' AS STRING) AS tag         FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL 
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_pace, 0)                    AS total, cm.month_offset, CAST('GBA' AS STRING) AS tag                 FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL            
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sold_estimates_pace, 0)         AS total, cm.month_offset, CAST('Sold Estimates' AS STRING) AS tag      FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL                 
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_sj_qty, 0)             AS total, cm.month_offset, CAST('Manpower' AS STRING) AS tag            FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sold_hours_total_sold_hrs, 0)   AS total, cm.month_offset, CAST('Sold Hours' AS STRING) AS tag          FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj__usd_100_total, 0)           AS total, cm.month_offset, CAST('SJ<$100' AS STRING) AS tag             FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.recalls_total, 0)               AS total, cm.month_offset, CAST('Recalls' AS STRING) AS tag             FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_pct_total, 0)         AS total, cm.month_offset, CAST('SJ Repair %' AS STRING) AS tag         FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_avg_usd_total, 0)     AS total, cm.month_offset, CAST('SJ Repair Avg$$' AS STRING) AS tag     FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_total, 0)    AS total, cm.month_offset, CAST('Opportunity TO %' AS STRING) AS tag    FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.to_conversion_pct_total, 0)     AS total, cm.month_offset, CAST('TO Conversion %' AS STRING) AS tag     FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.conversion_usd_avg_total, 0)    AS total, cm.month_offset, CAST('Conversion $Avg' AS STRING) AS tag     FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_total, 0)       AS total, cm.month_offset, CAST('SJ MKTEstimates' AS STRING) AS tag     FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_pct_total, 0)      AS total, cm.month_offset, CAST('SJ MKTE Conv %' AS STRING) AS tag      FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_usd_total, 0)      AS total, cm.month_offset, CAST('SJ MKTE Conv $' AS STRING) AS tag      FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.airflow_prj_mix_pct_total, 0)   AS total, cm.month_offset, CAST('Airflow PRJ MIX %' AS STRING) AS tag   FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.af_prj_avg_usd_total, 0)        AS total, cm.month_offset, CAST('AF PRJ AVG $' AS STRING) AS tag        FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
     SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_mix_pct_total, 0)        AS total, cm.month_offset, CAST('Equip MIX %' AS STRING) AS tag         FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_avg_usd_total, 0)         AS total, cm.month_offset, CAST('Equip AVG $' AS STRING) AS tag         FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL       
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_pct_total, 0)           AS total, cm.month_offset, CAST('SVC PRJ %' AS STRING) AS tag           FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month
     UNION ALL 
    SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_avg_usd_total, 0)       AS total, cm.month_offset, CAST('SVC PRJ AVG$' AS STRING) AS tag        FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month