ALL, ltm_kpis_data AS (
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_new_cust, 0) AS tag_value, cm.month_offset, CAST('REVENUE_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_ncust__trend, 0) AS tag_value, cm.month_offset, CAST('REVENUE_NCUST__TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('REVENUE_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_rcust__trend, 0) AS tag_value, cm.month_offset, CAST('REVENUE_RCUST__TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_demand, 0) AS tag_value, cm.month_offset, CAST('REVENUE_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_maint, 0) AS tag_value, cm.month_offset, CAST('REVENUE_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_estimates, 0) AS tag_value, cm.month_offset, CAST('REVENUE_ESTIMATES' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_projects, 0) AS tag_value, cm.month_offset, CAST('REVENUE_PROJECTS' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_total, 0) AS tag_value, cm.month_offset, CAST('REVENUE_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_pace, 0) AS tag_value, cm.month_offset, CAST('REVENUE_PACE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.revenue_rev_trend, 0) AS tag_value, cm.month_offset, CAST('REVENUE_REV_TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_new_cust, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_ncust__trend, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_NCUST__TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_new_cust_ib, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_NEW_CUST_IB' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_new_cust_ob, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_NEW_CUST_OB' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_r_cust_ob, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_R_CUST_OB' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_r_cust_ib, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_R_CUST_IB' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_r_cust_ib_pace, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_R_CUST_IB_PACE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_r_ib_trend, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_R_IB_TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_demand, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_maint, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_total, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_pace, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_PACE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.single_jobs_sj_trend, 0) AS tag_value, cm.month_offset, CAST('SINGLE_JOBS_SJ_TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_new_cust, 0) AS tag_value, cm.month_offset, CAST('GBA_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_r_cust, 0) AS tag_value, cm.month_offset, CAST('GBA_R_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_demand, 0) AS tag_value, cm.month_offset, CAST('GBA_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_maint, 0) AS tag_value, cm.month_offset, CAST('GBA_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_actual, 0) AS tag_value, cm.month_offset, CAST('GBA_ACTUAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_pace, 0) AS tag_value, cm.month_offset, CAST('GBA_PACE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.gba_trend, 0) AS tag_value, cm.month_offset, CAST('GBA_TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sold_estimates_actual, 0) AS tag_value, cm.month_offset, CAST('SOLD_ESTIMATES_ACTUAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sold_estimates_pace, 0) AS tag_value, cm.month_offset, CAST('SOLD_ESTIMATES_PACE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sold_estimates_trend, 0) AS tag_value, cm.month_offset, CAST('SOLD_ESTIMATES_TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_sj_qty, 0) AS tag_value, cm.month_offset, CAST('MANPOWER_SJ_QTY' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_svc_avg, 0) AS tag_value, cm.month_offset, CAST('MANPOWER_SVC_AVG' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_svc_pj_qty, 0) AS tag_value, cm.month_offset, CAST('MANPOWER_SVC_PJ_QTY' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_svc_prj_avg, 0) AS tag_value, cm.month_offset, CAST('MANPOWER_SVC_PRJ_AVG' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_repl_pj_qty, 0) AS tag_value, cm.month_offset, CAST('MANPOWER_REPL_PJ_QTY' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.manpower_installer_avg, 0) AS tag_value, cm.month_offset, CAST('MANPOWER_INSTALLER_AVG' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sold_hours_total_sold_hrs, 0) AS tag_value, cm.month_offset, CAST('SOLD_HOURS_TOTAL_SOLD_HRS' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj__usd_100_new_cust, 0) AS tag_value, cm.month_offset, CAST('SJ__USD_100_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj__usd_100_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SJ__USD_100_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj__usd_100_demand, 0) AS tag_value, cm.month_offset, CAST('SJ__USD_100_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj__usd_100_maint, 0) AS tag_value, cm.month_offset, CAST('SJ__USD_100_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj__usd_100_total, 0) AS tag_value, cm.month_offset, CAST('SJ__USD_100_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.recalls_total, 0) AS tag_value, cm.month_offset, CAST('RECALLS_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_pct_demand, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_PCT_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_pct_maint, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_PCT_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_pct_total, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_avg_usd_new_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_AVG_USD_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_avg_usd_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_AVG_USD_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_avg_usd_demand, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_AVG_USD_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_avg_usd_maint, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_AVG_USD_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_repair_avg_usd_total, 0) AS tag_value, cm.month_offset, CAST('SJ_REPAIR_AVG_USD_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('OPPORTUNITY_TO_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('OPPORTUNITY_TO_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_demand, 0) AS tag_value, cm.month_offset, CAST('OPPORTUNITY_TO_PCT_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_maint, 0) AS tag_value, cm.month_offset, CAST('OPPORTUNITY_TO_PCT_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_est, 0) AS tag_value, cm.month_offset, CAST('OPPORTUNITY_TO_PCT_EST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.opportunity_to_pct_total, 0) AS tag_value, cm.month_offset, CAST('OPPORTUNITY_TO_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.to_conversion_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('TO_CONVERSION_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.to_conversion_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('TO_CONVERSION_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.to_conversion_pct_demand, 0) AS tag_value, cm.month_offset, CAST('TO_CONVERSION_PCT_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.to_conversion_pct_maint, 0) AS tag_value, cm.month_offset, CAST('TO_CONVERSION_PCT_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.to_conversion_pct_total, 0) AS tag_value, cm.month_offset, CAST('TO_CONVERSION_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.conversion_usd_avg_new_cust, 0) AS tag_value, cm.month_offset, CAST('CONVERSION_USD_AVG_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.conversion_usd_avg_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('CONVERSION_USD_AVG_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.conversion_usd_avg_demand, 0) AS tag_value, cm.month_offset, CAST('CONVERSION_USD_AVG_DEMAND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.conversion_usd_avg_maint, 0) AS tag_value, cm.month_offset, CAST('CONVERSION_USD_AVG_MAINT' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.conversion_usd_avg_total, 0) AS tag_value, cm.month_offset, CAST('CONVERSION_USD_AVG_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_new_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTESTIMATES_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTESTIMATES_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_estimates, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTESTIMATES_ESTIMATES' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_total, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTESTIMATES_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_pace, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTESTIMATES_PACE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mktestimates_est_trend, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTESTIMATES_EST_TREND' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_pct_total, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_usd_new_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_USD_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_usd_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_USD_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_usd_estimates, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_USD_ESTIMATES' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.sj_mkte_conv_usd_total, 0) AS tag_value, cm.month_offset, CAST('SJ_MKTE_CONV_USD_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.airflow_prj_mix_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('AIRFLOW_PRJ_MIX_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.airflow_prj_mix_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('AIRFLOW_PRJ_MIX_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.airflow_prj_mix_pct_total, 0) AS tag_value, cm.month_offset, CAST('AIRFLOW_PRJ_MIX_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.af_prj_avg_usd_new_cust, 0) AS tag_value, cm.month_offset, CAST('AF_PRJ_AVG_USD_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.af_prj_avg_usd_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('AF_PRJ_AVG_USD_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.af_prj_avg_usd_total_prj, 0) AS tag_value, cm.month_offset, CAST('AF_PRJ_AVG_USD_TOTAL_PRJ' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_mix_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('EQUIP_MIX_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_mix_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('EQUIP_MIX_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_mix_pct_total, 0) AS tag_value, cm.month_offset, CAST('EQUIP_MIX_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_avg_usd_new_cust, 0) AS tag_value, cm.month_offset, CAST('EQUIP_AVG_USD_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_avg_usd_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('EQUIP_AVG_USD_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.equip_avg_usd_total, 0) AS tag_value, cm.month_offset, CAST('EQUIP_AVG_USD_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_pct_new_cust, 0) AS tag_value, cm.month_offset, CAST('SVC_PRJ_PCT_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_pct_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SVC_PRJ_PCT_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_pct_total, 0) AS tag_value, cm.month_offset, CAST('SVC_PRJ_PCT_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_avg_usd_new_cust, 0) AS tag_value, cm.month_offset, CAST('SVC_PRJ_AVG_USD_NEW_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_avg_usd_repeat_cust, 0) AS tag_value, cm.month_offset, CAST('SVC_PRJ_AVG_USD_REPEAT_CUST' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.svc_prj_avg_usd_total, 0) AS tag_value, cm.month_offset, CAST('SVC_PRJ_AVG_USD_TOTAL' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 
 UNION ALL
SELECT cm.company_new_name, cm.middle_point, cm.month_date, COALESCE(cr.tab_title, 0) AS tag_value, cm.month_offset, CAST('TAB_TITLE' AS STRING) AS tag FROM company_months cm LEFT JOIN `gp-technologies-dev.silver.ltm_kpis_consolidate_group` cr ON cm.company_new_name = cr.company_new_name AND EXTRACT(YEAR FROM cm.month_date) = cr.year AND EXTRACT(MONTH FROM cm.month_date) = cr.month 

